// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request for
/// [HubService.AcceptSpokeUpdate][google.cloud.networkconnectivity.v1.HubService.AcceptSpokeUpdate].
///
/// [google.cloud.networkconnectivity.v1.HubService.AcceptSpokeUpdate]: <doc:HubServiceClient/acceptSpokeUpdate(request:options:)>
public struct AcceptSpokeUpdateRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the hub to accept spoke update.
  public var name: Swift.String = Swift.String()

  /// Required. The URI of the spoke to accept update.
  public var spokeUri: Swift.String = Swift.String()

  /// Required. The etag of the spoke to accept update.
  public var spokeEtag: Swift.String = Swift.String()

  /// Optional. A request ID to identify requests. Specify a unique request ID so
  /// that if you must retry your request, the server knows to ignore the request
  /// if it has already been completed. The server guarantees that a request
  /// doesn't result in creation of duplicate commitments for at least 60
  /// minutes.
  ///
  /// For example, consider a situation where you make an initial request and
  /// the request times out. If you make the request again with the same request
  /// ID, the server can check to see whether the original operation
  /// was received. If it was, the server ignores the second request. This
  /// behavior prevents clients from mistakenly creating duplicate commitments.
  ///
  /// The request ID must be a valid UUID, with the exception that zero UUID is
  /// not supported (00000000-0000-0000-0000-000000000000).
  public var requestId: Swift.String = Swift.String()

  /// Initialize a new instance of `AcceptSpokeUpdateRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AcceptSpokeUpdateRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.AcceptSpokeUpdateRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
