// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class CrossNetworkAutomationServiceLogging: CrossNetworkAutomationServiceStub {
    let inner: any CrossNetworkAutomationServiceStub
    let logger: Logger

    public init(_ inner: any CrossNetworkAutomationServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-networkconnectivity-v1"
      logger[metadataKey: "gcp.client.service"] = "networkconnectivity"
      logger[metadataKey: "gcp.experimental.swift.client"] = "CrossNetworkAutomationService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listServiceConnectionMaps(
      request: ListServiceConnectionMapsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionMapsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listServiceConnectionMaps",
        action: {
          (r: ListServiceConnectionMapsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionMapsResponse
          in
          return try await self.inner.listServiceConnectionMaps(request: r, options: o)
        })
    }

    public func getServiceConnectionMap(
      request: GetServiceConnectionMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceConnectionMap {
      try await self._intercept(
        request: request,
        options: options,
        name: "getServiceConnectionMap",
        action: {
          (r: GetServiceConnectionMapRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.ServiceConnectionMap
          in
          return try await self.inner.getServiceConnectionMap(request: r, options: o)
        })
    }

    public func createServiceConnectionMap(
      request: CreateServiceConnectionMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createServiceConnectionMap",
        action: {
          (r: CreateServiceConnectionMapRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createServiceConnectionMap(request: r, options: o)
        })
    }

    public func updateServiceConnectionMap(
      request: UpdateServiceConnectionMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateServiceConnectionMap",
        action: {
          (r: UpdateServiceConnectionMapRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateServiceConnectionMap(request: r, options: o)
        })
    }

    public func deleteServiceConnectionMap(
      request: DeleteServiceConnectionMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteServiceConnectionMap",
        action: {
          (r: DeleteServiceConnectionMapRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteServiceConnectionMap(request: r, options: o)
        })
    }

    public func listServiceConnectionPolicies(
      request: ListServiceConnectionPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listServiceConnectionPolicies",
        action: {
          (r: ListServiceConnectionPoliciesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionPoliciesResponse
          in
          return try await self.inner.listServiceConnectionPolicies(request: r, options: o)
        })
    }

    public func getServiceConnectionPolicy(
      request: GetServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceConnectionPolicy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getServiceConnectionPolicy",
        action: {
          (r: GetServiceConnectionPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.ServiceConnectionPolicy
          in
          return try await self.inner.getServiceConnectionPolicy(request: r, options: o)
        })
    }

    public func createServiceConnectionPolicy(
      request: CreateServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createServiceConnectionPolicy",
        action: {
          (r: CreateServiceConnectionPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createServiceConnectionPolicy(request: r, options: o)
        })
    }

    public func updateServiceConnectionPolicy(
      request: UpdateServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateServiceConnectionPolicy",
        action: {
          (r: UpdateServiceConnectionPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateServiceConnectionPolicy(request: r, options: o)
        })
    }

    public func deleteServiceConnectionPolicy(
      request: DeleteServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteServiceConnectionPolicy",
        action: {
          (r: DeleteServiceConnectionPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteServiceConnectionPolicy(request: r, options: o)
        })
    }

    public func listServiceClasses(
      request: ListServiceClassesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceClassesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listServiceClasses",
        action: {
          (r: ListServiceClassesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.ListServiceClassesResponse
          in
          return try await self.inner.listServiceClasses(request: r, options: o)
        })
    }

    public func getServiceClass(
      request: GetServiceClassRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceClass {
      try await self._intercept(
        request: request,
        options: options,
        name: "getServiceClass",
        action: {
          (r: GetServiceClassRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.ServiceClass
          in
          return try await self.inner.getServiceClass(request: r, options: o)
        })
    }

    public func updateServiceClass(
      request: UpdateServiceClassRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateServiceClass",
        action: {
          (r: UpdateServiceClassRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateServiceClass(request: r, options: o)
        })
    }

    public func deleteServiceClass(
      request: DeleteServiceClassRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteServiceClass",
        action: {
          (r: DeleteServiceClassRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteServiceClass(request: r, options: o)
        })
    }

    public func getServiceConnectionToken(
      request: GetServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceConnectionToken {
      try await self._intercept(
        request: request,
        options: options,
        name: "getServiceConnectionToken",
        action: {
          (r: GetServiceConnectionTokenRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.ServiceConnectionToken
          in
          return try await self.inner.getServiceConnectionToken(request: r, options: o)
        })
    }

    public func listServiceConnectionTokens(
      request: ListServiceConnectionTokensRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionTokensResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listServiceConnectionTokens",
        action: {
          (r: ListServiceConnectionTokensRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionTokensResponse
          in
          return try await self.inner.listServiceConnectionTokens(request: r, options: o)
        })
    }

    public func createServiceConnectionToken(
      request: CreateServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createServiceConnectionToken",
        action: {
          (r: CreateServiceConnectionTokenRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createServiceConnectionToken(request: r, options: o)
        })
    }

    public func deleteServiceConnectionToken(
      request: DeleteServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteServiceConnectionToken",
        action: {
          (r: DeleteServiceConnectionTokenRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteServiceConnectionToken(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
