// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class CrossNetworkAutomationServiceRetry: CrossNetworkAutomationServiceStub {
    let inner: any CrossNetworkAutomationServiceStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any CrossNetworkAutomationServiceStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listServiceConnectionMaps(
      request: ListServiceConnectionMapsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionMapsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListServiceConnectionMapsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionMapsResponse
          in
          return try await self.inner.listServiceConnectionMaps(request: r, options: o)
        })
    }

    public func getServiceConnectionMap(
      request: GetServiceConnectionMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceConnectionMap {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetServiceConnectionMapRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.ServiceConnectionMap
          in
          return try await self.inner.getServiceConnectionMap(request: r, options: o)
        })
    }

    public func createServiceConnectionMap(
      request: CreateServiceConnectionMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateServiceConnectionMapRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createServiceConnectionMap(request: r, options: o)
        })
    }

    public func updateServiceConnectionMap(
      request: UpdateServiceConnectionMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateServiceConnectionMapRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateServiceConnectionMap(request: r, options: o)
        })
    }

    public func deleteServiceConnectionMap(
      request: DeleteServiceConnectionMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteServiceConnectionMapRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteServiceConnectionMap(request: r, options: o)
        })
    }

    public func listServiceConnectionPolicies(
      request: ListServiceConnectionPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListServiceConnectionPoliciesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionPoliciesResponse
          in
          return try await self.inner.listServiceConnectionPolicies(request: r, options: o)
        })
    }

    public func getServiceConnectionPolicy(
      request: GetServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceConnectionPolicy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetServiceConnectionPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.ServiceConnectionPolicy
          in
          return try await self.inner.getServiceConnectionPolicy(request: r, options: o)
        })
    }

    public func createServiceConnectionPolicy(
      request: CreateServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateServiceConnectionPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createServiceConnectionPolicy(request: r, options: o)
        })
    }

    public func updateServiceConnectionPolicy(
      request: UpdateServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateServiceConnectionPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateServiceConnectionPolicy(request: r, options: o)
        })
    }

    public func deleteServiceConnectionPolicy(
      request: DeleteServiceConnectionPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteServiceConnectionPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteServiceConnectionPolicy(request: r, options: o)
        })
    }

    public func listServiceClasses(
      request: ListServiceClassesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceClassesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListServiceClassesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.ListServiceClassesResponse
          in
          return try await self.inner.listServiceClasses(request: r, options: o)
        })
    }

    public func getServiceClass(
      request: GetServiceClassRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceClass {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetServiceClassRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.ServiceClass
          in
          return try await self.inner.getServiceClass(request: r, options: o)
        })
    }

    public func updateServiceClass(
      request: UpdateServiceClassRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateServiceClassRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateServiceClass(request: r, options: o)
        })
    }

    public func deleteServiceClass(
      request: DeleteServiceClassRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteServiceClassRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteServiceClass(request: r, options: o)
        })
    }

    public func getServiceConnectionToken(
      request: GetServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ServiceConnectionToken {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetServiceConnectionTokenRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.ServiceConnectionToken
          in
          return try await self.inner.getServiceConnectionToken(request: r, options: o)
        })
    }

    public func listServiceConnectionTokens(
      request: ListServiceConnectionTokensRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionTokensResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListServiceConnectionTokensRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.ListServiceConnectionTokensResponse
          in
          return try await self.inner.listServiceConnectionTokens(request: r, options: o)
        })
    }

    public func createServiceConnectionToken(
      request: CreateServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateServiceConnectionTokenRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createServiceConnectionToken(request: r, options: o)
        })
    }

    public func deleteServiceConnectionToken(
      request: DeleteServiceConnectionTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteServiceConnectionTokenRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteServiceConnectionToken(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
