// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class DataTransferServiceRetry: DataTransferServiceStub {
    let inner: any DataTransferServiceStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any DataTransferServiceStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listMulticloudDataTransferConfigs(
      request: ListMulticloudDataTransferConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListMulticloudDataTransferConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListMulticloudDataTransferConfigsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.ListMulticloudDataTransferConfigsResponse
          in
          return try await self.inner.listMulticloudDataTransferConfigs(request: r, options: o)
        })
    }

    public func getMulticloudDataTransferConfig(
      request: GetMulticloudDataTransferConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.MulticloudDataTransferConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetMulticloudDataTransferConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.MulticloudDataTransferConfig
          in
          return try await self.inner.getMulticloudDataTransferConfig(request: r, options: o)
        })
    }

    public func createMulticloudDataTransferConfig(
      request: CreateMulticloudDataTransferConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateMulticloudDataTransferConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createMulticloudDataTransferConfig(request: r, options: o)
        })
    }

    public func updateMulticloudDataTransferConfig(
      request: UpdateMulticloudDataTransferConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateMulticloudDataTransferConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateMulticloudDataTransferConfig(request: r, options: o)
        })
    }

    public func deleteMulticloudDataTransferConfig(
      request: DeleteMulticloudDataTransferConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteMulticloudDataTransferConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteMulticloudDataTransferConfig(request: r, options: o)
        })
    }

    public func listDestinations(
      request: ListDestinationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListDestinationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDestinationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.ListDestinationsResponse
          in
          return try await self.inner.listDestinations(request: r, options: o)
        })
    }

    public func getDestination(
      request: GetDestinationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.Destination {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDestinationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkConnectivityV1.Destination
          in
          return try await self.inner.getDestination(request: r, options: o)
        })
    }

    public func createDestination(
      request: CreateDestinationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateDestinationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createDestination(request: r, options: o)
        })
    }

    public func updateDestination(
      request: UpdateDestinationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateDestinationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateDestination(request: r, options: o)
        })
    }

    public func deleteDestination(
      request: DeleteDestinationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteDestinationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteDestination(request: r, options: o)
        })
    }

    public func getMulticloudDataTransferSupportedService(
      request: GetMulticloudDataTransferSupportedServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.MulticloudDataTransferSupportedService {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetMulticloudDataTransferSupportedServiceRequest, o: GoogleGax.RequestOptions)
            async throws -> GoogleCloudNetworkConnectivityV1.MulticloudDataTransferSupportedService
          in
          return try await self.inner.getMulticloudDataTransferSupportedService(
            request: r, options: o)
        })
    }

    public func listMulticloudDataTransferSupportedServices(
      request: ListMulticloudDataTransferSupportedServicesRequest, options: GoogleGax.RequestOptions
    ) async throws
      -> GoogleCloudNetworkConnectivityV1.ListMulticloudDataTransferSupportedServicesResponse
    {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListMulticloudDataTransferSupportedServicesRequest, o: GoogleGax.RequestOptions)
            async throws
            -> GoogleCloudNetworkConnectivityV1.ListMulticloudDataTransferSupportedServicesResponse
          in
          return try await self.inner.listMulticloudDataTransferSupportedServices(
            request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
