// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol DataTransferServiceStub: Sendable {
    func listMulticloudDataTransferConfigs(
      request: ListMulticloudDataTransferConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListMulticloudDataTransferConfigsResponse

    func getMulticloudDataTransferConfig(
      request: GetMulticloudDataTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.MulticloudDataTransferConfig

    func createMulticloudDataTransferConfig(
      request: CreateMulticloudDataTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateMulticloudDataTransferConfig(
      request: UpdateMulticloudDataTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteMulticloudDataTransferConfig(
      request: DeleteMulticloudDataTransferConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listDestinations(
      request: ListDestinationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListDestinationsResponse

    func getDestination(
      request: GetDestinationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.Destination

    func createDestination(
      request: CreateDestinationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateDestination(
      request: UpdateDestinationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteDestination(
      request: DeleteDestinationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getMulticloudDataTransferSupportedService(
      request: GetMulticloudDataTransferSupportedServiceRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.MulticloudDataTransferSupportedService

    func listMulticloudDataTransferSupportedServices(
      request: ListMulticloudDataTransferSupportedServicesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudNetworkConnectivityV1.ListMulticloudDataTransferSupportedServicesResponse

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
