// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A group represents a subset of spokes attached to a hub.
public struct Group: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Immutable. The name of the group. Group names must be unique. They
  /// use the following form:
  ///      `projects/{project_number}/locations/global/hubs/{hub}/groups/{group_id}`
  public var name: Swift.String = Swift.String()

  /// Output only. The time the group was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time the group was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. Labels in key-value pair format. For more information about
  /// labels, see [Requirements for
  /// labels](https://cloud.google.com/resource-manager/docs/creating-managing-labels#requirements).
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. The description of the group.
  public var description: Swift.String = Swift.String()

  /// Output only. The Google-generated UUID for the group. This value is unique
  /// across all group resources. If a group is deleted and
  /// another with the same name is created, the new route table is assigned
  /// a different unique_id.
  public var uid: Swift.String = Swift.String()

  /// Output only. The current lifecycle state of this group.
  public var state: State = State()

  /// Optional. The auto-accept setting for this group.
  public var autoAccept: AutoAccept? = nil

  /// Output only. The name of the route table that corresponds to this group.
  /// They use the following form:
  /// `projects/{project_number}/locations/global/hubs/{hub_id}/routeTables/{route_table_id}`
  public var routeTable: Swift.String = Swift.String()

  /// Initialize a new instance of `Group`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Group().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.Group"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
