// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A Network Connectivity Center hub is a global management resource to which
/// you attach spokes. A single hub can contain spokes from multiple regions.
/// However, if any of a hub's spokes use the site-to-site data transfer feature,
/// the resources associated with those spokes must all be in the same VPC
/// network. Spokes that do not use site-to-site data transfer can be associated
/// with any VPC network in your project.
public struct Hub: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Immutable. The name of the hub. Hub names must be unique. They use the
  /// following form:
  ///     `projects/{project_number}/locations/global/hubs/{hub_id}`
  public var name: Swift.String = Swift.String()

  /// Output only. The time the hub was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time the hub was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional labels in key-value pair format. For more information about
  /// labels, see [Requirements for
  /// labels](https://cloud.google.com/resource-manager/docs/creating-managing-labels#requirements).
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. An optional description of the hub.
  public var description: Swift.String = Swift.String()

  /// Output only. The Google-generated UUID for the hub. This value is unique
  /// across all hub resources. If a hub is deleted and another with the same
  /// name is created, the new hub is assigned a different unique_id.
  public var uniqueId: Swift.String = Swift.String()

  /// Output only. The current lifecycle state of this hub.
  public var state: State = State()

  /// The VPC networks associated with this hub's spokes.
  ///
  /// This field is read-only. Network Connectivity Center automatically
  /// populates it based on the set of spokes attached to the hub.
  public var routingVpcs: [RoutingVPC] = []

  /// Output only. The route tables that belong to this hub. They use the
  /// following form:
  ///    `projects/{project_number}/locations/global/hubs/{hub_id}/routeTables/{route_table_id}`
  ///
  /// This field is read-only. Network Connectivity Center automatically
  /// populates it based on the route tables nested under the hub.
  public var routeTables: [Swift.String] = []

  /// Output only. A summary of the spokes associated with a hub. The
  /// summary includes a count of spokes according to type
  /// and according to state. If any spokes are inactive,
  /// the summary also lists the reasons they are inactive,
  /// including a count for each reason.
  public var spokeSummary: SpokeSummary? = nil

  /// Optional. The policy mode of this hub. This field can be either
  /// PRESET or CUSTOM. If unspecified, the
  /// policy_mode defaults to PRESET.
  public var policyMode: PolicyMode = PolicyMode()

  /// Optional. The topology implemented in this hub. Currently, this field is
  /// only used when policy_mode = PRESET. The available preset topologies are
  /// MESH and STAR. If preset_topology is unspecified and policy_mode = PRESET,
  /// the preset_topology defaults to MESH. When policy_mode = CUSTOM,
  /// the preset_topology is set to PRESET_TOPOLOGY_UNSPECIFIED.
  public var presetTopology: PresetTopology = PresetTopology()

  /// Optional. Whether Private Service Connect connection propagation is enabled
  /// for the hub. If true, Private Service Connect endpoints in VPC spokes
  /// attached to the hub are made accessible to other VPC spokes attached to the
  /// hub. The default value is false.
  public var exportPsc: Swift.Bool? = nil

  /// Initialize a new instance of `Hub`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Hub().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.Hub"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
