// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol HubServiceStub: Sendable {
    func listHubs(
      request: ListHubsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListHubsResponse

    func getHub(
      request: GetHubRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.Hub

    func createHub(
      request: CreateHubRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateHub(
      request: UpdateHubRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteHub(
      request: DeleteHubRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listHubSpokes(
      request: ListHubSpokesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListHubSpokesResponse

    func queryHubStatus(
      request: QueryHubStatusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.QueryHubStatusResponse

    func listSpokes(
      request: ListSpokesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListSpokesResponse

    func getSpoke(
      request: GetSpokeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.Spoke

    func createSpoke(
      request: CreateSpokeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateSpoke(
      request: UpdateSpokeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func rejectHubSpoke(
      request: RejectHubSpokeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func acceptHubSpoke(
      request: AcceptHubSpokeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func acceptSpokeUpdate(
      request: AcceptSpokeUpdateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func rejectSpokeUpdate(
      request: RejectSpokeUpdateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteSpoke(
      request: DeleteSpokeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getRouteTable(
      request: GetRouteTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.RouteTable

    func getRoute(
      request: GetRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.Route

    func listRoutes(
      request: ListRoutesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListRoutesResponse

    func listRouteTables(
      request: ListRouteTablesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListRouteTablesResponse

    func getGroup(
      request: GetGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.Group

    func listGroups(
      request: ListGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListGroupsResponse

    func updateGroup(
      request: UpdateGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
