// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleIAMV1
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Network Connectivity Center is a hub-and-spoke abstraction for network
/// connectivity management in Google Cloud. It reduces operational complexity
/// through a simple, centralized connectivity management model.
///
/// @Snippet(path: "HubServiceQuickstart")
public final class HubServiceClient: Clients.HubServiceProtocol, Sendable {
  let inner: any Clients.HubServiceStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `HubServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.HubServiceStub = try Clients.HubServiceTransport(options)
    inner = Clients.HubServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.HubServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists the Network Connectivity Center hubs associated with a given project.
  ///
  /// @Snippet(path: "HubService_ListHubs")
  public func listHubs(
    request: ListHubsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListHubsResponse {
    try await self.inner.listHubs(request: request, options: options)
  }

  /// Gets details about a Network Connectivity Center hub.
  ///
  /// @Snippet(path: "HubService_GetHub")
  public func getHub(
    request: GetHubRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.Hub {
    try await self.inner.getHub(request: request, options: options)
  }

  /// Creates a new Network Connectivity Center hub in the specified project.
  ///
  /// @Snippet(path: "HubService_CreateHub")
  public func createHub(
    request: CreateHubRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createHub(request: request, options: options)
  }

  /// Creates a new Network Connectivity Center hub in the specified project.
  ///
  /// @Snippet(path: "HubService_CreateHub")
  public func createHubPollingUntilDone(
    request: CreateHubRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Hub> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Hub>.State in
      return try op._extractStatus(Hub.self)
    }
    let rawOp = try await self.createHub(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Hub>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the description and/or labels of a Network Connectivity Center
  /// hub.
  ///
  /// @Snippet(path: "HubService_UpdateHub")
  public func updateHub(
    request: UpdateHubRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateHub(request: request, options: options)
  }

  /// Updates the description and/or labels of a Network Connectivity Center
  /// hub.
  ///
  /// @Snippet(path: "HubService_UpdateHub")
  public func updateHubPollingUntilDone(
    request: UpdateHubRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Hub> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Hub>.State in
      return try op._extractStatus(Hub.self)
    }
    let rawOp = try await self.updateHub(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Hub>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a Network Connectivity Center hub.
  ///
  /// @Snippet(path: "HubService_DeleteHub")
  public func deleteHub(
    request: DeleteHubRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteHub(request: request, options: options)
  }

  /// Deletes a Network Connectivity Center hub.
  ///
  /// @Snippet(path: "HubService_DeleteHub")
  public func deleteHubPollingUntilDone(
    request: DeleteHubRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteHub(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists the Network Connectivity Center spokes associated with a
  /// specified hub and location. The list includes both spokes that are attached
  /// to the hub and spokes that have been proposed but not yet accepted.
  ///
  /// @Snippet(path: "HubService_ListHubSpokes")
  public func listHubSpokes(
    request: ListHubSpokesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListHubSpokesResponse {
    try await self.inner.listHubSpokes(request: request, options: options)
  }

  /// Query the Private Service Connect propagation status of a Network
  /// Connectivity Center hub.
  ///
  /// @Snippet(path: "HubService_QueryHubStatus")
  public func queryHubStatus(
    request: QueryHubStatusRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.QueryHubStatusResponse {
    try await self.inner.queryHubStatus(request: request, options: options)
  }

  /// Lists the Network Connectivity Center spokes in a specified project and
  /// location.
  ///
  /// @Snippet(path: "HubService_ListSpokes")
  public func listSpokes(
    request: ListSpokesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListSpokesResponse {
    try await self.inner.listSpokes(request: request, options: options)
  }

  /// Gets details about a Network Connectivity Center spoke.
  ///
  /// @Snippet(path: "HubService_GetSpoke")
  public func getSpoke(
    request: GetSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.Spoke {
    try await self.inner.getSpoke(request: request, options: options)
  }

  /// Creates a Network Connectivity Center spoke.
  ///
  /// @Snippet(path: "HubService_CreateSpoke")
  public func createSpoke(
    request: CreateSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createSpoke(request: request, options: options)
  }

  /// Creates a Network Connectivity Center spoke.
  ///
  /// @Snippet(path: "HubService_CreateSpoke")
  public func createSpokePollingUntilDone(
    request: CreateSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Spoke> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Spoke>.State in
      return try op._extractStatus(Spoke.self)
    }
    let rawOp = try await self.createSpoke(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Spoke>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a Network Connectivity Center spoke.
  ///
  /// @Snippet(path: "HubService_UpdateSpoke")
  public func updateSpoke(
    request: UpdateSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateSpoke(request: request, options: options)
  }

  /// Updates the parameters of a Network Connectivity Center spoke.
  ///
  /// @Snippet(path: "HubService_UpdateSpoke")
  public func updateSpokePollingUntilDone(
    request: UpdateSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Spoke> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Spoke>.State in
      return try op._extractStatus(Spoke.self)
    }
    let rawOp = try await self.updateSpoke(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Spoke>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Rejects a Network Connectivity Center spoke from being attached to a hub.
  /// If the spoke was previously in the `ACTIVE` state, it
  /// transitions to the `INACTIVE` state and is no longer able to
  /// connect to other spokes that are attached to the hub.
  ///
  /// @Snippet(path: "HubService_RejectHubSpoke")
  public func rejectHubSpoke(
    request: RejectHubSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.rejectHubSpoke(request: request, options: options)
  }

  /// Rejects a Network Connectivity Center spoke from being attached to a hub.
  /// If the spoke was previously in the `ACTIVE` state, it
  /// transitions to the `INACTIVE` state and is no longer able to
  /// connect to other spokes that are attached to the hub.
  ///
  /// @Snippet(path: "HubService_RejectHubSpoke")
  public func rejectHubSpokePollingUntilDone(
    request: RejectHubSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<RejectHubSpokeResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<RejectHubSpokeResponse>.State in
      return try op._extractStatus(RejectHubSpokeResponse.self)
    }
    let rawOp = try await self.rejectHubSpoke(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<RejectHubSpokeResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Accepts a proposal to attach a Network Connectivity Center spoke
  /// to a hub.
  ///
  /// @Snippet(path: "HubService_AcceptHubSpoke")
  public func acceptHubSpoke(
    request: AcceptHubSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.acceptHubSpoke(request: request, options: options)
  }

  /// Accepts a proposal to attach a Network Connectivity Center spoke
  /// to a hub.
  ///
  /// @Snippet(path: "HubService_AcceptHubSpoke")
  public func acceptHubSpokePollingUntilDone(
    request: AcceptHubSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AcceptHubSpokeResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AcceptHubSpokeResponse>.State in
      return try op._extractStatus(AcceptHubSpokeResponse.self)
    }
    let rawOp = try await self.acceptHubSpoke(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<AcceptHubSpokeResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Accepts a proposal to update a Network Connectivity Center spoke in a hub.
  ///
  /// @Snippet(path: "HubService_AcceptSpokeUpdate")
  public func acceptSpokeUpdate(
    request: AcceptSpokeUpdateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.acceptSpokeUpdate(request: request, options: options)
  }

  /// Accepts a proposal to update a Network Connectivity Center spoke in a hub.
  ///
  /// @Snippet(path: "HubService_AcceptSpokeUpdate")
  public func acceptSpokeUpdatePollingUntilDone(
    request: AcceptSpokeUpdateRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AcceptSpokeUpdateResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AcceptSpokeUpdateResponse>.State in
      return try op._extractStatus(AcceptSpokeUpdateResponse.self)
    }
    let rawOp = try await self.acceptSpokeUpdate(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<AcceptSpokeUpdateResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Rejects a proposal to update a Network Connectivity Center spoke in a hub.
  ///
  /// @Snippet(path: "HubService_RejectSpokeUpdate")
  public func rejectSpokeUpdate(
    request: RejectSpokeUpdateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.rejectSpokeUpdate(request: request, options: options)
  }

  /// Rejects a proposal to update a Network Connectivity Center spoke in a hub.
  ///
  /// @Snippet(path: "HubService_RejectSpokeUpdate")
  public func rejectSpokeUpdatePollingUntilDone(
    request: RejectSpokeUpdateRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<RejectSpokeUpdateResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<RejectSpokeUpdateResponse>.State in
      return try op._extractStatus(RejectSpokeUpdateResponse.self)
    }
    let rawOp = try await self.rejectSpokeUpdate(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<RejectSpokeUpdateResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a Network Connectivity Center spoke.
  ///
  /// @Snippet(path: "HubService_DeleteSpoke")
  public func deleteSpoke(
    request: DeleteSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteSpoke(request: request, options: options)
  }

  /// Deletes a Network Connectivity Center spoke.
  ///
  /// @Snippet(path: "HubService_DeleteSpoke")
  public func deleteSpokePollingUntilDone(
    request: DeleteSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteSpoke(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets details about a Network Connectivity Center route table.
  ///
  /// @Snippet(path: "HubService_GetRouteTable")
  public func getRouteTable(
    request: GetRouteTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.RouteTable {
    try await self.inner.getRouteTable(request: request, options: options)
  }

  /// Gets details about the specified route.
  ///
  /// @Snippet(path: "HubService_GetRoute")
  public func getRoute(
    request: GetRouteRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.Route {
    try await self.inner.getRoute(request: request, options: options)
  }

  /// Lists routes in a given route table.
  ///
  /// @Snippet(path: "HubService_ListRoutes")
  public func listRoutes(
    request: ListRoutesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListRoutesResponse {
    try await self.inner.listRoutes(request: request, options: options)
  }

  /// Lists route tables in a given hub.
  ///
  /// @Snippet(path: "HubService_ListRouteTables")
  public func listRouteTables(
    request: ListRouteTablesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListRouteTablesResponse {
    try await self.inner.listRouteTables(request: request, options: options)
  }

  /// Gets details about a Network Connectivity Center group.
  ///
  /// @Snippet(path: "HubService_GetGroup")
  public func getGroup(
    request: GetGroupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.Group {
    try await self.inner.getGroup(request: request, options: options)
  }

  /// Lists groups in a given hub.
  ///
  /// @Snippet(path: "HubService_ListGroups")
  public func listGroups(
    request: ListGroupsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListGroupsResponse {
    try await self.inner.listGroups(request: request, options: options)
  }

  /// Updates the parameters of a Network Connectivity Center group.
  ///
  /// @Snippet(path: "HubService_UpdateGroup")
  public func updateGroup(
    request: UpdateGroupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateGroup(request: request, options: options)
  }

  /// Updates the parameters of a Network Connectivity Center group.
  ///
  /// @Snippet(path: "HubService_UpdateGroup")
  public func updateGroupPollingUntilDone(
    request: UpdateGroupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Group> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Group>.State in
      return try op._extractStatus(Group.self)
    }
    let rawOp = try await self.updateGroup(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Group>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "HubService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "HubService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "HubService_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "HubService_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "HubService_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "HubService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "HubService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "HubService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "HubService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `HubServiceClient`.
  ///
  /// To mock `HubServiceClient` change your functions to receive
  /// `some HubServiceProtocol` or `any HubServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol HubServiceProtocol: Sendable {
    /// See `HubServiceClient.createHub`.
    func createHubPollingUntilDone(request: CreateHubRequest) async throws -> any GoogleGax
      .PollableOperation<Hub>

    /// See `HubServiceClient.createHub`.
    func createHubPollingUntilDone(
      parent: Swift.String,
      hub: Hub?,
      hubId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Hub>

    /// See `HubServiceClient.updateHub`.
    func updateHubPollingUntilDone(request: UpdateHubRequest) async throws -> any GoogleGax
      .PollableOperation<Hub>

    /// See `HubServiceClient.updateHub`.
    func updateHubPollingUntilDone(
      hub: Hub?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<Hub>

    /// See `HubServiceClient.deleteHub`.
    func deleteHubPollingUntilDone(request: DeleteHubRequest) async throws -> any GoogleGax
      .PollableOperation<Swift.Void>

    /// See `HubServiceClient.deleteHub`.
    func deleteHubPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `HubServiceClient.createSpoke`.
    func createSpokePollingUntilDone(request: CreateSpokeRequest) async throws -> any GoogleGax
      .PollableOperation<Spoke>

    /// See `HubServiceClient.createSpoke`.
    func createSpokePollingUntilDone(
      parent: Swift.String,
      spoke: Spoke?,
      spokeId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Spoke>

    /// See `HubServiceClient.updateSpoke`.
    func updateSpokePollingUntilDone(request: UpdateSpokeRequest) async throws -> any GoogleGax
      .PollableOperation<Spoke>

    /// See `HubServiceClient.updateSpoke`.
    func updateSpokePollingUntilDone(
      spoke: Spoke?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<Spoke>

    /// See `HubServiceClient.rejectHubSpoke`.
    func rejectHubSpokePollingUntilDone(request: RejectHubSpokeRequest) async throws
      -> any GoogleGax.PollableOperation<RejectHubSpokeResponse>

    /// See `HubServiceClient.rejectHubSpoke`.
    func rejectHubSpokePollingUntilDone(
      name: Swift.String,
      spokeUri: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<RejectHubSpokeResponse>

    /// See `HubServiceClient.acceptHubSpoke`.
    func acceptHubSpokePollingUntilDone(request: AcceptHubSpokeRequest) async throws
      -> any GoogleGax.PollableOperation<AcceptHubSpokeResponse>

    /// See `HubServiceClient.acceptHubSpoke`.
    func acceptHubSpokePollingUntilDone(
      name: Swift.String,
      spokeUri: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<AcceptHubSpokeResponse>

    /// See `HubServiceClient.acceptSpokeUpdate`.
    func acceptSpokeUpdatePollingUntilDone(request: AcceptSpokeUpdateRequest) async throws
      -> any GoogleGax.PollableOperation<AcceptSpokeUpdateResponse>

    /// See `HubServiceClient.acceptSpokeUpdate`.
    func acceptSpokeUpdatePollingUntilDone(
      name: Swift.String,
      spokeUri: Swift.String,
      spokeEtag: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<AcceptSpokeUpdateResponse>

    /// See `HubServiceClient.rejectSpokeUpdate`.
    func rejectSpokeUpdatePollingUntilDone(request: RejectSpokeUpdateRequest) async throws
      -> any GoogleGax.PollableOperation<RejectSpokeUpdateResponse>

    /// See `HubServiceClient.rejectSpokeUpdate`.
    func rejectSpokeUpdatePollingUntilDone(
      name: Swift.String,
      spokeUri: Swift.String,
      spokeEtag: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<RejectSpokeUpdateResponse>

    /// See `HubServiceClient.deleteSpoke`.
    func deleteSpokePollingUntilDone(request: DeleteSpokeRequest) async throws -> any GoogleGax
      .PollableOperation<Swift.Void>

    /// See `HubServiceClient.deleteSpoke`.
    func deleteSpokePollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `HubServiceClient.updateGroup`.
    func updateGroupPollingUntilDone(request: UpdateGroupRequest) async throws -> any GoogleGax
      .PollableOperation<Group>

    /// See `HubServiceClient.updateGroup`.
    func updateGroupPollingUntilDone(
      group: Group?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<Group>

    /// See `HubServiceClient.listHubs`.
    func listHubs(
      request: ListHubsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListHubsResponse

    /// See `HubServiceClient.getHub`.
    func getHub(
      request: GetHubRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.Hub

    /// See `HubServiceClient.createHub`.
    func createHub(
      request: CreateHubRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `HubServiceClient.createHub`.
    func createHubPollingUntilDone(
      request: CreateHubRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Hub>

    /// See `HubServiceClient.updateHub`.
    func updateHub(
      request: UpdateHubRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `HubServiceClient.updateHub`.
    func updateHubPollingUntilDone(
      request: UpdateHubRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Hub>

    /// See `HubServiceClient.deleteHub`.
    func deleteHub(
      request: DeleteHubRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `HubServiceClient.deleteHub`.
    func deleteHubPollingUntilDone(
      request: DeleteHubRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `HubServiceClient.listHubSpokes`.
    func listHubSpokes(
      request: ListHubSpokesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListHubSpokesResponse

    /// See `HubServiceClient.queryHubStatus`.
    func queryHubStatus(
      request: QueryHubStatusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.QueryHubStatusResponse

    /// See `HubServiceClient.listSpokes`.
    func listSpokes(
      request: ListSpokesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListSpokesResponse

    /// See `HubServiceClient.getSpoke`.
    func getSpoke(
      request: GetSpokeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.Spoke

    /// See `HubServiceClient.createSpoke`.
    func createSpoke(
      request: CreateSpokeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `HubServiceClient.createSpoke`.
    func createSpokePollingUntilDone(
      request: CreateSpokeRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Spoke>

    /// See `HubServiceClient.updateSpoke`.
    func updateSpoke(
      request: UpdateSpokeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `HubServiceClient.updateSpoke`.
    func updateSpokePollingUntilDone(
      request: UpdateSpokeRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Spoke>

    /// See `HubServiceClient.rejectHubSpoke`.
    func rejectHubSpoke(
      request: RejectHubSpokeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `HubServiceClient.rejectHubSpoke`.
    func rejectHubSpokePollingUntilDone(
      request: RejectHubSpokeRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<RejectHubSpokeResponse>

    /// See `HubServiceClient.acceptHubSpoke`.
    func acceptHubSpoke(
      request: AcceptHubSpokeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `HubServiceClient.acceptHubSpoke`.
    func acceptHubSpokePollingUntilDone(
      request: AcceptHubSpokeRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AcceptHubSpokeResponse>

    /// See `HubServiceClient.acceptSpokeUpdate`.
    func acceptSpokeUpdate(
      request: AcceptSpokeUpdateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `HubServiceClient.acceptSpokeUpdate`.
    func acceptSpokeUpdatePollingUntilDone(
      request: AcceptSpokeUpdateRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AcceptSpokeUpdateResponse>

    /// See `HubServiceClient.rejectSpokeUpdate`.
    func rejectSpokeUpdate(
      request: RejectSpokeUpdateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `HubServiceClient.rejectSpokeUpdate`.
    func rejectSpokeUpdatePollingUntilDone(
      request: RejectSpokeUpdateRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<RejectSpokeUpdateResponse>

    /// See `HubServiceClient.deleteSpoke`.
    func deleteSpoke(
      request: DeleteSpokeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `HubServiceClient.deleteSpoke`.
    func deleteSpokePollingUntilDone(
      request: DeleteSpokeRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `HubServiceClient.getRouteTable`.
    func getRouteTable(
      request: GetRouteTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.RouteTable

    /// See `HubServiceClient.getRoute`.
    func getRoute(
      request: GetRouteRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.Route

    /// See `HubServiceClient.listRoutes`.
    func listRoutes(
      request: ListRoutesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListRoutesResponse

    /// See `HubServiceClient.listRouteTables`.
    func listRouteTables(
      request: ListRouteTablesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListRouteTablesResponse

    /// See `HubServiceClient.getGroup`.
    func getGroup(
      request: GetGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.Group

    /// See `HubServiceClient.listGroups`.
    func listGroups(
      request: ListGroupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListGroupsResponse

    /// See `HubServiceClient.updateGroup`.
    func updateGroup(
      request: UpdateGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `HubServiceClient.updateGroup`.
    func updateGroupPollingUntilDone(
      request: UpdateGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Group>

    /// See `HubServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `HubServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `HubServiceClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `HubServiceClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `HubServiceClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `HubServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `HubServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `HubServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.HubServiceProtocol {
  public func listHubs(request: ListHubsRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.ListHubsResponse
  {
    try await self.listHubs(request: request, options: .init())
  }

  public func listHubs(
    request: ListHubsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListHubsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listHubs(
    byItem: ListHubsRequest
  ) -> any AsyncSequence<Hub, Swift.Error> {
    self.listHubs(byItem: byItem, options: .init())
  }

  /// Lists the Network Connectivity Center hubs associated with a given project.
  ///
  /// @Snippet(path: "HubService_ListHubs")
  public func listHubs(
    byItem: ListHubsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Hub, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudNetworkConnectivityV1.ListHubsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listHubs(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listHubs(
    parent: Swift.String,
  ) -> any AsyncSequence<Hub, Swift.Error> {
    let request = ListHubsRequest().with {
      $0.parent = parent
    }
    return self.listHubs(byItem: request)
  }

  public func getHub(request: GetHubRequest) async throws -> GoogleCloudNetworkConnectivityV1.Hub {
    try await self.getHub(request: request, options: .init())
  }

  public func getHub(
    request: GetHubRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.Hub {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getHub(
    name: Swift.String,
  ) async throws -> GoogleCloudNetworkConnectivityV1.Hub {
    let request = GetHubRequest().with {
      $0.name = name
    }
    return try await self.getHub(request: request)
  }

  public func createHub(request: CreateHubRequest) async throws -> GoogleLongRunning.Operation {
    try await self.createHub(request: request, options: .init())
  }

  public func createHub(
    request: CreateHubRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createHubPollingUntilDone(request: CreateHubRequest) async throws -> any GoogleGax
    .PollableOperation<Hub>
  {
    try await self.createHubPollingUntilDone(request: request, options: .init())
  }

  public func createHubPollingUntilDone(
    request: CreateHubRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Hub> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Hub>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createHubPollingUntilDone(
    parent: Swift.String,
    hub: Hub?,
    hubId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Hub> {
    let request = CreateHubRequest().with {
      $0.parent = parent
      $0.hub = hub
      $0.hubId = hubId
    }
    return try await self.createHubPollingUntilDone(request: request)
  }

  public func updateHub(request: UpdateHubRequest) async throws -> GoogleLongRunning.Operation {
    try await self.updateHub(request: request, options: .init())
  }

  public func updateHub(
    request: UpdateHubRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateHubPollingUntilDone(request: UpdateHubRequest) async throws -> any GoogleGax
    .PollableOperation<Hub>
  {
    try await self.updateHubPollingUntilDone(request: request, options: .init())
  }

  public func updateHubPollingUntilDone(
    request: UpdateHubRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Hub> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Hub>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateHubPollingUntilDone(
    hub: Hub?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Hub> {
    let request = UpdateHubRequest().with {
      $0.hub = hub
      $0.updateMask = updateMask
    }
    return try await self.updateHubPollingUntilDone(request: request)
  }

  public func deleteHub(request: DeleteHubRequest) async throws -> GoogleLongRunning.Operation {
    try await self.deleteHub(request: request, options: .init())
  }

  public func deleteHub(
    request: DeleteHubRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteHubPollingUntilDone(request: DeleteHubRequest) async throws -> any GoogleGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteHubPollingUntilDone(request: request, options: .init())
  }

  public func deleteHubPollingUntilDone(
    request: DeleteHubRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteHubPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteHubRequest().with {
      $0.name = name
    }
    return try await self.deleteHubPollingUntilDone(request: request)
  }

  public func listHubSpokes(request: ListHubSpokesRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.ListHubSpokesResponse
  {
    try await self.listHubSpokes(request: request, options: .init())
  }

  public func listHubSpokes(
    request: ListHubSpokesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListHubSpokesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listHubSpokes(
    byItem: ListHubSpokesRequest
  ) -> any AsyncSequence<Spoke, Swift.Error> {
    self.listHubSpokes(byItem: byItem, options: .init())
  }

  /// Lists the Network Connectivity Center spokes associated with a
  /// specified hub and location. The list includes both spokes that are attached
  /// to the hub and spokes that have been proposed but not yet accepted.
  ///
  /// @Snippet(path: "HubService_ListHubSpokes")
  public func listHubSpokes(
    byItem: ListHubSpokesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Spoke, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudNetworkConnectivityV1.ListHubSpokesResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listHubSpokes(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listHubSpokes(
    name: Swift.String,
  ) -> any AsyncSequence<Spoke, Swift.Error> {
    let request = ListHubSpokesRequest().with {
      $0.name = name
    }
    return self.listHubSpokes(byItem: request)
  }

  public func queryHubStatus(request: QueryHubStatusRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.QueryHubStatusResponse
  {
    try await self.queryHubStatus(request: request, options: .init())
  }

  public func queryHubStatus(
    request: QueryHubStatusRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.QueryHubStatusResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func queryHubStatus(
    byItem: QueryHubStatusRequest
  ) -> any AsyncSequence<HubStatusEntry, Swift.Error> {
    self.queryHubStatus(byItem: byItem, options: .init())
  }

  /// Query the Private Service Connect propagation status of a Network
  /// Connectivity Center hub.
  ///
  /// @Snippet(path: "HubService_QueryHubStatus")
  public func queryHubStatus(
    byItem: QueryHubStatusRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<HubStatusEntry, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudNetworkConnectivityV1.QueryHubStatusResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.queryHubStatus(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func queryHubStatus(
    name: Swift.String,
  ) -> any AsyncSequence<HubStatusEntry, Swift.Error> {
    let request = QueryHubStatusRequest().with {
      $0.name = name
    }
    return self.queryHubStatus(byItem: request)
  }

  public func listSpokes(request: ListSpokesRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.ListSpokesResponse
  {
    try await self.listSpokes(request: request, options: .init())
  }

  public func listSpokes(
    request: ListSpokesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListSpokesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listSpokes(
    byItem: ListSpokesRequest
  ) -> any AsyncSequence<Spoke, Swift.Error> {
    self.listSpokes(byItem: byItem, options: .init())
  }

  /// Lists the Network Connectivity Center spokes in a specified project and
  /// location.
  ///
  /// @Snippet(path: "HubService_ListSpokes")
  public func listSpokes(
    byItem: ListSpokesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Spoke, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudNetworkConnectivityV1.ListSpokesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listSpokes(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listSpokes(
    parent: Swift.String,
  ) -> any AsyncSequence<Spoke, Swift.Error> {
    let request = ListSpokesRequest().with {
      $0.parent = parent
    }
    return self.listSpokes(byItem: request)
  }

  public func getSpoke(request: GetSpokeRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.Spoke
  {
    try await self.getSpoke(request: request, options: .init())
  }

  public func getSpoke(
    request: GetSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.Spoke {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getSpoke(
    name: Swift.String,
  ) async throws -> GoogleCloudNetworkConnectivityV1.Spoke {
    let request = GetSpokeRequest().with {
      $0.name = name
    }
    return try await self.getSpoke(request: request)
  }

  public func createSpoke(request: CreateSpokeRequest) async throws -> GoogleLongRunning.Operation {
    try await self.createSpoke(request: request, options: .init())
  }

  public func createSpoke(
    request: CreateSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createSpokePollingUntilDone(request: CreateSpokeRequest) async throws -> any GoogleGax
    .PollableOperation<Spoke>
  {
    try await self.createSpokePollingUntilDone(request: request, options: .init())
  }

  public func createSpokePollingUntilDone(
    request: CreateSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Spoke> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Spoke>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createSpokePollingUntilDone(
    parent: Swift.String,
    spoke: Spoke?,
    spokeId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Spoke> {
    let request = CreateSpokeRequest().with {
      $0.parent = parent
      $0.spoke = spoke
      $0.spokeId = spokeId
    }
    return try await self.createSpokePollingUntilDone(request: request)
  }

  public func updateSpoke(request: UpdateSpokeRequest) async throws -> GoogleLongRunning.Operation {
    try await self.updateSpoke(request: request, options: .init())
  }

  public func updateSpoke(
    request: UpdateSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateSpokePollingUntilDone(request: UpdateSpokeRequest) async throws -> any GoogleGax
    .PollableOperation<Spoke>
  {
    try await self.updateSpokePollingUntilDone(request: request, options: .init())
  }

  public func updateSpokePollingUntilDone(
    request: UpdateSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Spoke> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Spoke>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateSpokePollingUntilDone(
    spoke: Spoke?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Spoke> {
    let request = UpdateSpokeRequest().with {
      $0.spoke = spoke
      $0.updateMask = updateMask
    }
    return try await self.updateSpokePollingUntilDone(request: request)
  }

  public func rejectHubSpoke(request: RejectHubSpokeRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.rejectHubSpoke(request: request, options: .init())
  }

  public func rejectHubSpoke(
    request: RejectHubSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func rejectHubSpokePollingUntilDone(request: RejectHubSpokeRequest) async throws
    -> any GoogleGax.PollableOperation<RejectHubSpokeResponse>
  {
    try await self.rejectHubSpokePollingUntilDone(request: request, options: .init())
  }

  public func rejectHubSpokePollingUntilDone(
    request: RejectHubSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<RejectHubSpokeResponse> {
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<RejectHubSpokeResponse>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func rejectHubSpokePollingUntilDone(
    name: Swift.String,
    spokeUri: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<RejectHubSpokeResponse> {
    let request = RejectHubSpokeRequest().with {
      $0.name = name
      $0.spokeUri = spokeUri
    }
    return try await self.rejectHubSpokePollingUntilDone(request: request)
  }

  public func acceptHubSpoke(request: AcceptHubSpokeRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.acceptHubSpoke(request: request, options: .init())
  }

  public func acceptHubSpoke(
    request: AcceptHubSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func acceptHubSpokePollingUntilDone(request: AcceptHubSpokeRequest) async throws
    -> any GoogleGax.PollableOperation<AcceptHubSpokeResponse>
  {
    try await self.acceptHubSpokePollingUntilDone(request: request, options: .init())
  }

  public func acceptHubSpokePollingUntilDone(
    request: AcceptHubSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AcceptHubSpokeResponse> {
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<AcceptHubSpokeResponse>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func acceptHubSpokePollingUntilDone(
    name: Swift.String,
    spokeUri: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<AcceptHubSpokeResponse> {
    let request = AcceptHubSpokeRequest().with {
      $0.name = name
      $0.spokeUri = spokeUri
    }
    return try await self.acceptHubSpokePollingUntilDone(request: request)
  }

  public func acceptSpokeUpdate(request: AcceptSpokeUpdateRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.acceptSpokeUpdate(request: request, options: .init())
  }

  public func acceptSpokeUpdate(
    request: AcceptSpokeUpdateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func acceptSpokeUpdatePollingUntilDone(request: AcceptSpokeUpdateRequest) async throws
    -> any GoogleGax.PollableOperation<AcceptSpokeUpdateResponse>
  {
    try await self.acceptSpokeUpdatePollingUntilDone(request: request, options: .init())
  }

  public func acceptSpokeUpdatePollingUntilDone(
    request: AcceptSpokeUpdateRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AcceptSpokeUpdateResponse> {
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<AcceptSpokeUpdateResponse>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func acceptSpokeUpdatePollingUntilDone(
    name: Swift.String,
    spokeUri: Swift.String,
    spokeEtag: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<AcceptSpokeUpdateResponse> {
    let request = AcceptSpokeUpdateRequest().with {
      $0.name = name
      $0.spokeUri = spokeUri
      $0.spokeEtag = spokeEtag
    }
    return try await self.acceptSpokeUpdatePollingUntilDone(request: request)
  }

  public func rejectSpokeUpdate(request: RejectSpokeUpdateRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.rejectSpokeUpdate(request: request, options: .init())
  }

  public func rejectSpokeUpdate(
    request: RejectSpokeUpdateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func rejectSpokeUpdatePollingUntilDone(request: RejectSpokeUpdateRequest) async throws
    -> any GoogleGax.PollableOperation<RejectSpokeUpdateResponse>
  {
    try await self.rejectSpokeUpdatePollingUntilDone(request: request, options: .init())
  }

  public func rejectSpokeUpdatePollingUntilDone(
    request: RejectSpokeUpdateRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<RejectSpokeUpdateResponse> {
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<RejectSpokeUpdateResponse>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func rejectSpokeUpdatePollingUntilDone(
    name: Swift.String,
    spokeUri: Swift.String,
    spokeEtag: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<RejectSpokeUpdateResponse> {
    let request = RejectSpokeUpdateRequest().with {
      $0.name = name
      $0.spokeUri = spokeUri
      $0.spokeEtag = spokeEtag
    }
    return try await self.rejectSpokeUpdatePollingUntilDone(request: request)
  }

  public func deleteSpoke(request: DeleteSpokeRequest) async throws -> GoogleLongRunning.Operation {
    try await self.deleteSpoke(request: request, options: .init())
  }

  public func deleteSpoke(
    request: DeleteSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteSpokePollingUntilDone(request: DeleteSpokeRequest) async throws -> any GoogleGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteSpokePollingUntilDone(request: request, options: .init())
  }

  public func deleteSpokePollingUntilDone(
    request: DeleteSpokeRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteSpokePollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteSpokeRequest().with {
      $0.name = name
    }
    return try await self.deleteSpokePollingUntilDone(request: request)
  }

  public func getRouteTable(request: GetRouteTableRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.RouteTable
  {
    try await self.getRouteTable(request: request, options: .init())
  }

  public func getRouteTable(
    request: GetRouteTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.RouteTable {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getRouteTable(
    name: Swift.String,
  ) async throws -> GoogleCloudNetworkConnectivityV1.RouteTable {
    let request = GetRouteTableRequest().with {
      $0.name = name
    }
    return try await self.getRouteTable(request: request)
  }

  public func getRoute(request: GetRouteRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.Route
  {
    try await self.getRoute(request: request, options: .init())
  }

  public func getRoute(
    request: GetRouteRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.Route {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getRoute(
    name: Swift.String,
  ) async throws -> GoogleCloudNetworkConnectivityV1.Route {
    let request = GetRouteRequest().with {
      $0.name = name
    }
    return try await self.getRoute(request: request)
  }

  public func listRoutes(request: ListRoutesRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.ListRoutesResponse
  {
    try await self.listRoutes(request: request, options: .init())
  }

  public func listRoutes(
    request: ListRoutesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListRoutesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listRoutes(
    byItem: ListRoutesRequest
  ) -> any AsyncSequence<Route, Swift.Error> {
    self.listRoutes(byItem: byItem, options: .init())
  }

  /// Lists routes in a given route table.
  ///
  /// @Snippet(path: "HubService_ListRoutes")
  public func listRoutes(
    byItem: ListRoutesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Route, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudNetworkConnectivityV1.ListRoutesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listRoutes(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listRoutes(
    parent: Swift.String,
  ) -> any AsyncSequence<Route, Swift.Error> {
    let request = ListRoutesRequest().with {
      $0.parent = parent
    }
    return self.listRoutes(byItem: request)
  }

  public func listRouteTables(request: ListRouteTablesRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.ListRouteTablesResponse
  {
    try await self.listRouteTables(request: request, options: .init())
  }

  public func listRouteTables(
    request: ListRouteTablesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListRouteTablesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listRouteTables(
    byItem: ListRouteTablesRequest
  ) -> any AsyncSequence<RouteTable, Swift.Error> {
    self.listRouteTables(byItem: byItem, options: .init())
  }

  /// Lists route tables in a given hub.
  ///
  /// @Snippet(path: "HubService_ListRouteTables")
  public func listRouteTables(
    byItem: ListRouteTablesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<RouteTable, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudNetworkConnectivityV1.ListRouteTablesResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listRouteTables(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listRouteTables(
    parent: Swift.String,
  ) -> any AsyncSequence<RouteTable, Swift.Error> {
    let request = ListRouteTablesRequest().with {
      $0.parent = parent
    }
    return self.listRouteTables(byItem: request)
  }

  public func getGroup(request: GetGroupRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.Group
  {
    try await self.getGroup(request: request, options: .init())
  }

  public func getGroup(
    request: GetGroupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.Group {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getGroup(
    name: Swift.String,
  ) async throws -> GoogleCloudNetworkConnectivityV1.Group {
    let request = GetGroupRequest().with {
      $0.name = name
    }
    return try await self.getGroup(request: request)
  }

  public func listGroups(request: ListGroupsRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.ListGroupsResponse
  {
    try await self.listGroups(request: request, options: .init())
  }

  public func listGroups(
    request: ListGroupsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListGroupsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listGroups(
    byItem: ListGroupsRequest
  ) -> any AsyncSequence<Group, Swift.Error> {
    self.listGroups(byItem: byItem, options: .init())
  }

  /// Lists groups in a given hub.
  ///
  /// @Snippet(path: "HubService_ListGroups")
  public func listGroups(
    byItem: ListGroupsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Group, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudNetworkConnectivityV1.ListGroupsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listGroups(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listGroups(
    parent: Swift.String,
  ) -> any AsyncSequence<Group, Swift.Error> {
    let request = ListGroupsRequest().with {
      $0.parent = parent
    }
    return self.listGroups(byItem: request)
  }

  public func updateGroup(request: UpdateGroupRequest) async throws -> GoogleLongRunning.Operation {
    try await self.updateGroup(request: request, options: .init())
  }

  public func updateGroup(
    request: UpdateGroupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateGroupPollingUntilDone(request: UpdateGroupRequest) async throws -> any GoogleGax
    .PollableOperation<Group>
  {
    try await self.updateGroupPollingUntilDone(request: request, options: .init())
  }

  public func updateGroupPollingUntilDone(
    request: UpdateGroupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Group> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Group>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateGroupPollingUntilDone(
    group: Group?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Group> {
    let request = UpdateGroupRequest().with {
      $0.group = group
      $0.updateMask = updateMask
    }
    return try await self.updateGroupPollingUntilDone(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    self.listLocations(byItem: byItem, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "HubService_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    self.listOperations(byItem: byItem, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "HubService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
