// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// The CLH-based service for internal range resources used to perform IPAM
/// operations within a VPC network.
///
/// @Snippet(path: "InternalRangeServiceQuickstart")
public final class InternalRangeServiceClient: Clients.InternalRangeServiceProtocol, Sendable {
  let inner: any Clients.InternalRangeServiceStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `InternalRangeServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.InternalRangeServiceStub = try Clients.InternalRangeServiceTransport(
      options)
    inner = Clients.InternalRangeServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.InternalRangeServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists internal ranges in a given project and location.
  ///
  /// @Snippet(path: "InternalRangeService_ListInternalRanges")
  public func listInternalRanges(
    request: ListInternalRangesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListInternalRangesResponse {
    try await self.inner.listInternalRanges(request: request, options: options)
  }

  /// Lists internal ranges in a given project and location.
  ///
  /// @Snippet(path: "InternalRangeService_ListInternalRanges")
  public func listInternalRanges(
    byItem: ListInternalRangesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<InternalRange, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudNetworkConnectivityV1.ListInternalRangesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listInternalRanges(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single internal range.
  ///
  /// @Snippet(path: "InternalRangeService_GetInternalRange")
  public func getInternalRange(
    request: GetInternalRangeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.InternalRange {
    try await self.inner.getInternalRange(request: request, options: options)
  }

  /// Creates a new internal range in a given project and location.
  ///
  /// @Snippet(path: "InternalRangeService_CreateInternalRange")
  public func createInternalRange(
    request: CreateInternalRangeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createInternalRange(request: request, options: options)
  }

  /// Creates a new internal range in a given project and location.
  ///
  /// @Snippet(path: "InternalRangeService_CreateInternalRange")
  public func createInternalRange(
    withPolling: CreateInternalRangeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<InternalRange> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<InternalRange>.State in
      return try op._extractStatus(InternalRange.self)
    }
    let rawOp = try await self.createInternalRange(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<InternalRange>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a single internal range.
  ///
  /// @Snippet(path: "InternalRangeService_UpdateInternalRange")
  public func updateInternalRange(
    request: UpdateInternalRangeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateInternalRange(request: request, options: options)
  }

  /// Updates the parameters of a single internal range.
  ///
  /// @Snippet(path: "InternalRangeService_UpdateInternalRange")
  public func updateInternalRange(
    withPolling: UpdateInternalRangeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<InternalRange> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<InternalRange>.State in
      return try op._extractStatus(InternalRange.self)
    }
    let rawOp = try await self.updateInternalRange(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<InternalRange>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single internal range.
  ///
  /// @Snippet(path: "InternalRangeService_DeleteInternalRange")
  public func deleteInternalRange(
    request: DeleteInternalRangeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteInternalRange(request: request, options: options)
  }

  /// Deletes a single internal range.
  ///
  /// @Snippet(path: "InternalRangeService_DeleteInternalRange")
  public func deleteInternalRange(
    withPolling: DeleteInternalRangeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteInternalRange(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "InternalRangeService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "InternalRangeService_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "InternalRangeService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "InternalRangeService_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "InternalRangeService_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "InternalRangeService_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "InternalRangeService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "InternalRangeService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "InternalRangeService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "InternalRangeService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "InternalRangeService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `InternalRangeServiceClient`.
  ///
  /// To mock `InternalRangeServiceClient` change your functions to receive
  /// `some InternalRangeServiceProtocol` or `any InternalRangeServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol InternalRangeServiceProtocol {
    /// See `InternalRangeServiceClient.listInternalRanges`.
    func listInternalRanges(request: ListInternalRangesRequest) async throws
      -> GoogleCloudNetworkConnectivityV1.ListInternalRangesResponse

    /// See `InternalRangeServiceClient.listInternalRanges`.
    func listInternalRanges(
      byItem: ListInternalRangesRequest
    ) throws -> any AsyncSequence<InternalRange, Swift.Error>

    /// See `InternalRangeServiceClient.listInternalRanges`.
    func listInternalRanges(
      parent: Swift.String,
    ) throws -> any AsyncSequence<InternalRange, Swift.Error>

    /// See `InternalRangeServiceClient.getInternalRange`.
    func getInternalRange(request: GetInternalRangeRequest) async throws
      -> GoogleCloudNetworkConnectivityV1.InternalRange

    /// See `InternalRangeServiceClient.getInternalRange`.
    func getInternalRange(
      name: Swift.String,
    ) async throws -> GoogleCloudNetworkConnectivityV1.InternalRange

    /// See `InternalRangeServiceClient.createInternalRange`.
    func createInternalRange(request: CreateInternalRangeRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `InternalRangeServiceClient.createInternalRange`.
    func createInternalRange(withPolling: CreateInternalRangeRequest) async throws
      -> any GoogleCloudGax.PollableOperation<InternalRange>

    /// See `InternalRangeServiceClient.createInternalRange`.
    func createInternalRange(
      parent: Swift.String,
      internalRange: InternalRange?,
      internalRangeId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<InternalRange>

    /// See `InternalRangeServiceClient.updateInternalRange`.
    func updateInternalRange(request: UpdateInternalRangeRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `InternalRangeServiceClient.updateInternalRange`.
    func updateInternalRange(withPolling: UpdateInternalRangeRequest) async throws
      -> any GoogleCloudGax.PollableOperation<InternalRange>

    /// See `InternalRangeServiceClient.updateInternalRange`.
    func updateInternalRange(
      internalRange: InternalRange?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<InternalRange>

    /// See `InternalRangeServiceClient.deleteInternalRange`.
    func deleteInternalRange(request: DeleteInternalRangeRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `InternalRangeServiceClient.deleteInternalRange`.
    func deleteInternalRange(withPolling: DeleteInternalRangeRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `InternalRangeServiceClient.deleteInternalRange`.
    func deleteInternalRange(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `InternalRangeServiceClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `InternalRangeServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `InternalRangeServiceClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `InternalRangeServiceClient.setIamPolicy`.
    func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `InternalRangeServiceClient.getIamPolicy`.
    func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `InternalRangeServiceClient.testIamPermissions`.
    func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
      -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `InternalRangeServiceClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `InternalRangeServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `InternalRangeServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `InternalRangeServiceClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `InternalRangeServiceClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `InternalRangeServiceClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `InternalRangeServiceClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `InternalRangeServiceClient.listInternalRanges`.
    func listInternalRanges(
      request: ListInternalRangesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.ListInternalRangesResponse

    /// See `InternalRangeServiceClient.listInternalRanges`.
    func listInternalRanges(
      byItem: ListInternalRangesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<InternalRange, Swift.Error>

    /// See `InternalRangeServiceClient.getInternalRange`.
    func getInternalRange(
      request: GetInternalRangeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkConnectivityV1.InternalRange

    /// See `InternalRangeServiceClient.createInternalRange`.
    func createInternalRange(
      request: CreateInternalRangeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `InternalRangeServiceClient.createInternalRange`.
    func createInternalRange(
      withPolling: CreateInternalRangeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<InternalRange>

    /// See `InternalRangeServiceClient.updateInternalRange`.
    func updateInternalRange(
      request: UpdateInternalRangeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `InternalRangeServiceClient.updateInternalRange`.
    func updateInternalRange(
      withPolling: UpdateInternalRangeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<InternalRange>

    /// See `InternalRangeServiceClient.deleteInternalRange`.
    func deleteInternalRange(
      request: DeleteInternalRangeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `InternalRangeServiceClient.deleteInternalRange`.
    func deleteInternalRange(
      withPolling: DeleteInternalRangeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `InternalRangeServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `InternalRangeServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `InternalRangeServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `InternalRangeServiceClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `InternalRangeServiceClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `InternalRangeServiceClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `InternalRangeServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `InternalRangeServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `InternalRangeServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `InternalRangeServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.InternalRangeServiceProtocol {
  public func listInternalRanges(request: ListInternalRangesRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.ListInternalRangesResponse
  {
    try await self.listInternalRanges(request: request, options: .init())
  }

  public func listInternalRanges(
    request: ListInternalRangesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.ListInternalRangesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listInternalRanges(
    byItem: ListInternalRangesRequest
  ) throws -> any AsyncSequence<InternalRange, Swift.Error> {
    try self.listInternalRanges(byItem: byItem, options: .init())
  }

  public func listInternalRanges(
    byItem: ListInternalRangesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<InternalRange, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudNetworkConnectivityV1.ListInternalRangesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listInternalRanges(
    parent: Swift.String,
  ) throws -> any AsyncSequence<InternalRange, Swift.Error> {
    let request = ListInternalRangesRequest().with {
      $0.parent = parent
    }
    return try self.listInternalRanges(byItem: request)
  }

  public func getInternalRange(request: GetInternalRangeRequest) async throws
    -> GoogleCloudNetworkConnectivityV1.InternalRange
  {
    try await self.getInternalRange(request: request, options: .init())
  }

  public func getInternalRange(
    request: GetInternalRangeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudNetworkConnectivityV1.InternalRange {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getInternalRange(
    name: Swift.String,
  ) async throws -> GoogleCloudNetworkConnectivityV1.InternalRange {
    let request = GetInternalRangeRequest().with {
      $0.name = name
    }
    return try await self.getInternalRange(request: request)
  }

  public func createInternalRange(request: CreateInternalRangeRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createInternalRange(request: request, options: .init())
  }

  public func createInternalRange(
    request: CreateInternalRangeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createInternalRange(withPolling: CreateInternalRangeRequest) async throws
    -> any GoogleCloudGax.PollableOperation<InternalRange>
  {
    try await self.createInternalRange(withPolling: withPolling, options: .init())
  }

  public func createInternalRange(
    withPolling: CreateInternalRangeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<InternalRange> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<InternalRange>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createInternalRange(
    parent: Swift.String,
    internalRange: InternalRange?,
    internalRangeId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<InternalRange> {
    let request = CreateInternalRangeRequest().with {
      $0.parent = parent
      $0.internalRange = internalRange
      $0.internalRangeId = internalRangeId
    }
    return try await self.createInternalRange(withPolling: request)
  }

  public func updateInternalRange(request: UpdateInternalRangeRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateInternalRange(request: request, options: .init())
  }

  public func updateInternalRange(
    request: UpdateInternalRangeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateInternalRange(withPolling: UpdateInternalRangeRequest) async throws
    -> any GoogleCloudGax.PollableOperation<InternalRange>
  {
    try await self.updateInternalRange(withPolling: withPolling, options: .init())
  }

  public func updateInternalRange(
    withPolling: UpdateInternalRangeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<InternalRange> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<InternalRange>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateInternalRange(
    internalRange: InternalRange?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<InternalRange> {
    let request = UpdateInternalRangeRequest().with {
      $0.internalRange = internalRange
      $0.updateMask = updateMask
    }
    return try await self.updateInternalRange(withPolling: request)
  }

  public func deleteInternalRange(request: DeleteInternalRangeRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteInternalRange(request: request, options: .init())
  }

  public func deleteInternalRange(
    request: DeleteInternalRangeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteInternalRange(withPolling: DeleteInternalRangeRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deleteInternalRange(withPolling: withPolling, options: .init())
  }

  public func deleteInternalRange(
    withPolling: DeleteInternalRangeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteInternalRange(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteInternalRangeRequest().with {
      $0.name = name
    }
    return try await self.deleteInternalRange(withPolling: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
