// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A collection of Cloud VPN tunnel resources. These resources should be
/// redundant HA VPN tunnels that all advertise the same prefixes to Google
/// Cloud. Alternatively, in a passive/active configuration, all tunnels
/// should be capable of advertising the same prefixes.
public struct LinkedVpnTunnels: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The URIs of linked VPN tunnel resources.
  public var uris: [Swift.String] = []

  /// A value that controls whether site-to-site data transfer is enabled for
  /// these resources. Data transfer is available only in [supported
  /// locations](https://cloud.google.com/network-connectivity/docs/network-connectivity-center/concepts/locations).
  public var siteToSiteDataTransfer: Swift.Bool = Swift.Bool()

  /// Output only. The VPC network where these VPN tunnels are located.
  public var vpcNetwork: Swift.String = Swift.String()

  /// Optional. IP ranges allowed to be included during import from hub (does not
  /// control transit connectivity). The only allowed value for now is
  /// "ALL_IPV4_RANGES".
  public var includeImportRanges: [Swift.String] = []

  /// Initialize a new instance of `LinkedVpnTunnels`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LinkedVpnTunnels().with { $0.uris = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.LinkedVpnTunnels"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
