// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The request for
/// [HubService.ListHubSpokes][google.cloud.networkconnectivity.v1.HubService.ListHubSpokes].
///
///
/// [google.cloud.networkconnectivity.v1.HubService.ListHubSpokes]: <doc:HubServiceClient/listHubSpokes(request:options:)>
public struct ListHubSpokesRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the hub.
  public var name: Swift.String = Swift.String()

  /// A list of locations.
  /// Specify one of the following: `[global]`, a single region (for
  /// example, `[us-central1]`), or a combination of
  /// values (for example, `[global, us-central1, us-west1]`).
  /// If the spoke_locations field is populated, the list of results
  /// includes only spokes in the specified location.
  /// If the spoke_locations field is not populated, the list of results
  /// includes spokes in all locations.
  public var spokeLocations: [Swift.String] = []

  /// The maximum number of results to return per page.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The page token.
  public var pageToken: Swift.String = Swift.String()

  /// An expression that filters the list of results.
  public var filter: Swift.String = Swift.String()

  /// Sort the results by name or create_time.
  public var orderBy: Swift.String = Swift.String()

  /// The view of the spoke to return.
  /// The view that you use determines which spoke fields are included in the
  /// response.
  public var view: ListHubSpokesRequest.SpokeView = ListHubSpokesRequest.SpokeView()

  /// Initialize a new instance of `ListHubSpokesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListHubSpokesRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Enum that controls which spoke fields are included in the response.
  public enum SpokeView: Codable, Equatable, Sendable {
    /// The spoke view is unspecified. When the spoke view is unspecified, the
    /// API returns the same fields as the `BASIC` view.
    case unspecified
    /// Includes `name`, `create_time`, `hub`, `unique_id`, `state`, `reasons`,
    /// and `spoke_type`. This is the default value.
    case basic
    /// Includes all spoke fields except `labels`.
    /// You can use the `DETAILED` view only when you set the `spoke_locations`
    /// field to `[global]`.
    case detailed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .basic: return 1
      case .detailed: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SPOKE_VIEW_UNSPECIFIED"
      case .basic: return "BASIC"
      case .detailed: return "DETAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SpokeView/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SPOKE_VIEW_UNSPECIFIED": self = .unspecified
      case "BASIC": self = .basic
      case "DETAILED": self = .detailed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SpokeView/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .basic
      case 2: self = .detailed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .basic: return try container.encode(1)
      case .detailed: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.ListHubSpokesRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
