// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The status of one or more propagated Private Service Connect connections in a
/// hub.
public struct PscPropagationStatus: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the spoke that the source forwarding rule belongs to.
  public var sourceSpoke: Swift.String = Swift.String()

  /// The name of the group that the source spoke belongs to.
  public var sourceGroup: Swift.String = Swift.String()

  /// The name of the forwarding rule exported to the hub.
  public var sourceForwardingRule: Swift.String = Swift.String()

  /// The name of the spoke that the source forwarding rule propagates to.
  public var targetSpoke: Swift.String = Swift.String()

  /// The name of the group that the target spoke belongs to.
  public var targetGroup: Swift.String = Swift.String()

  /// The propagation status.
  public var code: PscPropagationStatus.Code = PscPropagationStatus.Code()

  /// The human-readable summary of the Private Service Connect connection
  /// propagation status.
  public var message: Swift.String = Swift.String()

  /// Initialize a new instance of `PscPropagationStatus`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PscPropagationStatus().with { $0.sourceSpoke = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The Code enum represents the state of the Private Service Connect
  /// propagation.
  public enum Code: Codable, Equatable, Sendable {
    /// The code is unspecified.
    case unspecified
    /// The propagated Private Service Connect connection is ready.
    case ready
    /// The Private Service Connect connection is propagating. This is a
    /// transient state.
    case propagating
    /// The Private Service Connect connection propagation failed because the VPC
    /// network or the project of the target spoke has exceeded the connection
    /// limit set by the producer.
    case errorProducerPropagatedConnectionLimitExceeded
    /// The Private Service Connect connection propagation failed because the NAT
    /// IP subnet space has been exhausted. It is equivalent to the `Needs
    /// attention` status of the Private Service Connect connection. See
    /// https://cloud.google.com/vpc/docs/about-accessing-vpc-hosted-services-endpoints#connection-statuses.
    case errorProducerNatIpSpaceExhausted
    /// The Private Service Connect connection propagation failed because the
    /// `PSC_ILB_CONSUMER_FORWARDING_RULES_PER_PRODUCER_NETWORK` quota in the
    /// producer VPC network has been exceeded.
    case errorProducerQuotaExceeded
    /// The Private Service Connect connection propagation failed because the
    /// `PSC_PROPAGATED_CONNECTIONS_PER_VPC_NETWORK` quota in the consumer
    /// VPC network has been exceeded.
    case errorConsumerQuotaExceeded
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ready: return 1
      case .propagating: return 2
      case .errorProducerPropagatedConnectionLimitExceeded: return 3
      case .errorProducerNatIpSpaceExhausted: return 4
      case .errorProducerQuotaExceeded: return 5
      case .errorConsumerQuotaExceeded: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CODE_UNSPECIFIED"
      case .ready: return "READY"
      case .propagating: return "PROPAGATING"
      case .errorProducerPropagatedConnectionLimitExceeded:
        return "ERROR_PRODUCER_PROPAGATED_CONNECTION_LIMIT_EXCEEDED"
      case .errorProducerNatIpSpaceExhausted: return "ERROR_PRODUCER_NAT_IP_SPACE_EXHAUSTED"
      case .errorProducerQuotaExceeded: return "ERROR_PRODUCER_QUOTA_EXCEEDED"
      case .errorConsumerQuotaExceeded: return "ERROR_CONSUMER_QUOTA_EXCEEDED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CODE_UNSPECIFIED": self = .unspecified
      case "READY": self = .ready
      case "PROPAGATING": self = .propagating
      case "ERROR_PRODUCER_PROPAGATED_CONNECTION_LIMIT_EXCEEDED":
        self = .errorProducerPropagatedConnectionLimitExceeded
      case "ERROR_PRODUCER_NAT_IP_SPACE_EXHAUSTED": self = .errorProducerNatIpSpaceExhausted
      case "ERROR_PRODUCER_QUOTA_EXCEEDED": self = .errorProducerQuotaExceeded
      case "ERROR_CONSUMER_QUOTA_EXCEEDED": self = .errorConsumerQuotaExceeded
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ready
      case 2: self = .propagating
      case 3: self = .errorProducerPropagatedConnectionLimitExceeded
      case 4: self = .errorProducerNatIpSpaceExhausted
      case 5: self = .errorProducerQuotaExceeded
      case 6: self = .errorConsumerQuotaExceeded
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .ready: return try container.encode(1)
      case .propagating: return try container.encode(2)
      case .errorProducerPropagatedConnectionLimitExceeded: return try container.encode(3)
      case .errorProducerNatIpSpaceExhausted: return try container.encode(4)
      case .errorProducerQuotaExceeded: return try container.encode(5)
      case .errorConsumerQuotaExceeded: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.PscPropagationStatus"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
