// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request for
/// [HubService.QueryHubStatus][google.cloud.networkconnectivity.v1.HubService.QueryHubStatus].
///
/// [google.cloud.networkconnectivity.v1.HubService.QueryHubStatus]: <doc:HubServiceClient/queryHubStatus(request:)>
public struct QueryHubStatusRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the hub.
  public var name: Swift.String = Swift.String()

  /// Optional. The maximum number of results to return per page.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The page token.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. An expression that filters the list of results.
  /// The filter can be used to filter the results by the following fields:
  ///   * `psc_propagation_status.source_spoke`
  ///   * `psc_propagation_status.source_group`
  ///   * `psc_propagation_status.source_forwarding_rule`
  ///   * `psc_propagation_status.target_spoke`
  ///   * `psc_propagation_status.target_group`
  ///   * `psc_propagation_status.code`
  ///   * `psc_propagation_status.message`
  public var filter: Swift.String = Swift.String()

  /// Optional. Sort the results in ascending order by the specified fields.
  /// A comma-separated list of any of these fields:
  ///   * `psc_propagation_status.source_spoke`
  ///   * `psc_propagation_status.source_group`
  ///   * `psc_propagation_status.source_forwarding_rule`
  ///   * `psc_propagation_status.target_spoke`
  ///   * `psc_propagation_status.target_group`
  ///   * `psc_propagation_status.code`
  /// If `group_by` is set, the value of the `order_by` field must be the
  /// same as or a subset of the `group_by` field.
  public var orderBy: Swift.String = Swift.String()

  /// Optional. Aggregate the results by the specified fields.
  /// A comma-separated list of any of these fields:
  ///   * `psc_propagation_status.source_spoke`
  ///   * `psc_propagation_status.source_group`
  ///   * `psc_propagation_status.source_forwarding_rule`
  ///   * `psc_propagation_status.target_spoke`
  ///   * `psc_propagation_status.target_group`
  ///   * `psc_propagation_status.code`
  public var groupBy: Swift.String = Swift.String()

  /// Initialize a new instance of `QueryHubStatusRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QueryHubStatusRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.QueryHubStatusRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
