// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The ServiceClass resource.
public struct ServiceClass: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Immutable. The name of a ServiceClass resource.
  /// Format:
  /// projects/{project}/locations/{location}/serviceClasses/{service_class}
  /// See: https://google.aip.dev/122#fields-representing-resource-names
  public var name: Swift.String = Swift.String()

  /// Output only. The generated service class name. Use this name to refer to
  /// the Service class in Service Connection Maps and Service Connection
  /// Policies.
  public var serviceClass: Swift.String = Swift.String()

  /// Output only. Time when the ServiceClass was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Time when the ServiceClass was updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// User-defined labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// A description of this resource.
  public var description: Swift.String = Swift.String()

  /// Optional. The etag is computed by the server, and may be sent on update and
  /// delete requests to ensure the client has an up-to-date value before
  /// proceeding.
  public var etag: Swift.String? = nil

  /// Initialize a new instance of `ServiceClass`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ServiceClass().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceClass"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
