// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The ServiceConnectionToken resource.
public struct ServiceConnectionToken: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Immutable. The name of a ServiceConnectionToken.
  /// Format:
  /// projects/{project}/locations/{location}/ServiceConnectionTokens/{service_connection_token}
  /// See: https://google.aip.dev/122#fields-representing-resource-names
  public var name: Swift.String = Swift.String()

  /// Output only. Time when the ServiceConnectionToken was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Time when the ServiceConnectionToken was updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// User-defined labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// A description of this resource.
  public var description: Swift.String = Swift.String()

  /// The resource path of the network associated with this token.
  /// Example:
  /// projects/{projectNumOrId}/global/networks/{resourceId}.
  public var network: Swift.String = Swift.String()

  /// Output only. The token generated by Automation.
  public var token: Swift.String = Swift.String()

  /// Output only. The time to which this token is valid.
  public var expireTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. The etag is computed by the server, and may be sent on update and
  /// delete requests to ensure the client has an up-to-date value before
  /// proceeding.
  public var etag: Swift.String? = nil

  /// Initialize a new instance of `ServiceConnectionToken`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ServiceConnectionToken().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkconnectivity.v1.ServiceConnectionToken"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
